@startuml Sequence_diagram

title Example processFile(JSON) call
'Handle Rivet creation
Frontend -> RivetController: HTTP POST (JSON) processFile(JSON)
RivetController -> RivetProcessor: Rivet(filecontents,riveters,confidence)
RivetProcessor -> GeneDateRiveter: apply(column)
GeneDateRiveter --> RivetProcessor: rivetedColumn
RivetProcessor -> DateRiveter: apply(column)
DateRiveter --> RivetProcessor: rivetedColumn
RivetProcessor -> CSVInjectionRiveter: apply(column)
CSVInjectionRiveter --> RivetProcessor: rivetedColumn
note right of RivetProcessor: Continues for as many riveters as needed
...

RivetController -> RivetProcessor: getFileContents()
RivetProcessor --> RivetController: DataFrame
RivetController --> Frontend: JSON

@enduml