@startuml Sequence_diagram

title Example processFile(JSON) call
'Handle Rivet creation
Frontend -> RivetController: HTTP POST (JSON) processFile(JSON)
RivetController -> RivetIO: parse(filecontents, args)
RivetIO -> Rivet: Rivet(filecontents,riveters,confidence)
Rivet --> RivetIO: Rivet
RivetIO --> RivetController: Rivet

'Apply Riveters
RivetController -> Rivet: applyRivets()
Rivet -> GeneDateRiveter: apply(column)
GeneDateRiveter --> Rivet: rivetedColumn
Rivet -> DateRiveter: apply(column)
DateRiveter --> Rivet: rivetedColumn
Rivet -> CSVInjectionRiveter: apply(column)
CSVInjectionRiveter --> Rivet: rivetedColumn
note right of Rivet: Continues for as many riveters as needed
...

RivetController -> Rivet: getFileContents()
Rivet --> RivetController: DataFrame
RivetController --> Frontend: JSON

@enduml