@startuml Web Interface Design
actor WebUser
actor/ EndWebUser
' Excel files and artifacts
    file WebCSV
    file ModifiedWebCSV

    artifact HomePage
    artifact AnalyzePage
    artifact DownloadPage

'Three interfaces to run
cloud Server {
    card AnalyzeFile
    card ProcessFile
}

database MongoDB [
        <b>MongoDB</b>
        CSV Size,
        User Country
    ]

component RosieRivet #FAC800 {
        card RivetFileAnalyzer
        card RivetProcessor 
        'within riveters, have Apply AND Analyze functions
        component Riveters {
            card Riveter

            card MetaRiveter
            card MesaRiveter 

            Riveter -- MetaRiveter 
            Riveter -- MesaRiveter

            card GeneDateRiveter
            card LargeIntRiveter
            card CSVInjectionRiveter
            card DateFormatRiveter
            card LocaleSeparatorRiveter
            card SYLKRiveter

            MesaRiveter -- GeneDateRiveter
            MesaRiveter -- LargeIntRiveter
            MesaRiveter -- CSVInjectionRiveter
            MesaRiveter -- DateFormatRiveter
            MetaRiveter -- LocaleSeparatorRiveter
            MetaRiveter -- SYLKRiveter
        }
        RivetFileAnalyzer .. Riveter : utilizes
        RivetProcessor .. Riveter : utilizes
        
    }

    WebUser -[hidden] EndWebUser
    ' WEB INTERFACE FLOW
    MongoDB <. AnalyzeFile : Sends data to store

    WebUser == WebCSV
    WebUser .. AnalyzePage : Provides Input \n (Includes rejecting file processing)
    WebCSV ==> HomePage
    HomePage ==> AnalyzeFile
    AnalyzeFile ===> RivetFileAnalyzer : Return File Analysis
    RivetFileAnalyzer ===> AnalyzeFile 
    AnalyzeFile ==> AnalyzePage

    AnalyzePage ==> ProcessFile
    ProcessFile ===> RivetProcessor
    RivetProcessor ===> ProcessFile : Return Processed File
    DownloadPage <= ProcessFile
    ModifiedWebCSV == DownloadPage
    EndWebUser <== ModifiedWebCSV : downloads file

    'FORMATTING FOR WEBUSER TO BE HAPPY
    MongoDB -[hidden] HomePage
    HomePage -[hidden] AnalyzePage
    AnalyzePage -[hidden] DownloadPage

@enduml