@startuml
    skinparam FontSize 18

    'Three users, order them
    actor WebUser 
    actor ExcelUser
    actor CLIUser

    ' Order the users (will be hidden)

    ' Web files and artifacts
    file WebCSV
    file ModifiedWebCSV
    artifact HomePage
    artifact AnalyzePage
    artifact DownloadPage

    ' CLI files and artifacts
    file CLI_CSV
    

    ' Excel Files and artifacts
    file ExcelCSV

    'Three interfaces to run
    cloud Server {
        card AnalyzeFile
        card ProcessFile
    }

    node ExcelRunner {
        card AnalyzeFile_Excel
        card ProcessFileExcel
    }

    node RivetCLI {
        card AnalyzeFile_CLI
        card ProcessFile_CLI
    }
    component RosieRivet #FAC800 {
        card RivetFileAnalyzer
        card RivetProcessor
        'within riveters, have Apply AND Analyze functions
        component Riveters {
            card Riveter
            card GeneDateRiveter
            card LargeIntRiveter
            card CSVInjectionRiveter
            card DateFormatRiveter

            Riveter -- GeneDateRiveter
            Riveter -- LargeIntRiveter
            Riveter -- CSVInjectionRiveter
            Riveter -- DateFormatRiveter
        }
        RivetFileAnalyzer .. Riveter : utilizes
        RivetProcessor .. Riveter : utilizes
        
    }

    database MongoDB [
        <b>MongoDB</b>
        CSV Size,
        User Country
    ]

    'USERS 
    WebUser -- WebCSV
    ExcelUser -- ExcelCSV 
    CLIUser -- CLI_CSV
    ' WEB INTERFACE FLOW
    MongoDB <-- AnalyzeFile

    
    WebCSV --> HomePage : Uploads
    AnalyzeFile <-- HomePage
    
    AnalyzeFile --- RivetFileAnalyzer
    AnalyzeFile_Excel --- RivetFileAnalyzer
    AnalyzeFile_CLI --- RivetFileAnalyzer

    AnalyzePage <-- AnalyzeFile
    WebUser ..> AnalyzePage : Provides input
    AnalyzePage --> ProcessFile
    
    
    DownloadPage <-- ProcessFile
    ProcessFile --- RivetProcessor
    ProcessFileExcel --- RivetProcessor
    ProcessFile_CLI --- RivetProcessor


    ModifiedWebCSV <-- DownloadPage
    WebUser <-- ModifiedWebCSV : Downloads

    'FORMATTING FOR WEBUSER TO BE HAPPY
    MongoDB -[hidden] HomePage
    HomePage -[hidden] AnalyzePage
    AnalyzePage -[hidden] DownloadPage


    ExcelCSV -- ExcelRunner
    
    CLI_CSV -- RivetCLI

    

@enduml